// Generated by delombok at Fri Jan 01 22:07:35 EST 2016
/******************************************************************************
 * Copyright (C) 2015 Yevgeny Krasik                                          *
 *                                                                            *
 * Licensed under the Apache License, Version 2.0 (the "License");            *
 * you may not use this file except in compliance with the License.           *
 * You may obtain a copy of the License at                                    *
 *                                                                            *
 * http://www.apache.org/licenses/LICENSE-2.0                                 *
 *                                                                            *
 * Unless required by applicable law or agreed to in writing, software        *
 * distributed under the License is distributed on an "AS IS" BASIS,          *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   *
 * See the License for the specific language governing permissions and        *
 * limitations under the License.                                             *
 ******************************************************************************/
package com.github.ykrasik.jaci.cli.assist;



/**
 * Assistance information for a command's parameters.
 * Includes parameters that were already bound (and parsed) as well as auto-complete suggestions for the next parameter.
 *
 * @author Yevgeny Krasik
 */
public class ParamAssistInfo {
    
    /**
     * The parameters that have already been parsed, as well as the next parameter to parse, if one exists.
     */

    private final BoundParams boundParams;
    
    /**
     * Auto-complete suggestions for the next parameter to parse.
     */

    private final AutoComplete autoComplete;

    //@java.beans.ConstructorProperties({"boundParams", "autoComplete"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public ParamAssistInfo( final BoundParams boundParams,  final AutoComplete autoComplete) {
        if (boundParams == null) {
            throw new java.lang.NullPointerException("boundParams");
        }
        if (autoComplete == null) {
            throw new java.lang.NullPointerException("autoComplete");
        }
        this.boundParams = boundParams;
        this.autoComplete = autoComplete;
    }

    /**
     * The parameters that have already been parsed, as well as the next parameter to parse, if one exists.
     */

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public BoundParams getBoundParams() {
        return this.boundParams;
    }

    /**
     * Auto-complete suggestions for the next parameter to parse.
     */

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public AutoComplete getAutoComplete() {
        return this.autoComplete;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ParamAssistInfo)) return false;
        final ParamAssistInfo other = (ParamAssistInfo)o;
        if (!other.canEqual((java.lang.Object)this)) return false;
        final java.lang.Object this$boundParams = this.getBoundParams();
        final java.lang.Object other$boundParams = other.getBoundParams();
        if (this$boundParams == null ? other$boundParams != null : !this$boundParams.equals(other$boundParams)) return false;
        final java.lang.Object this$autoComplete = this.getAutoComplete();
        final java.lang.Object other$autoComplete = other.getAutoComplete();
        if (this$autoComplete == null ? other$autoComplete != null : !this$autoComplete.equals(other$autoComplete)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ParamAssistInfo;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $boundParams = this.getBoundParams();
        result = result * PRIME + ($boundParams == null ? 43 : $boundParams.hashCode());
        final java.lang.Object $autoComplete = this.getAutoComplete();
        result = result * PRIME + ($autoComplete == null ? 43 : $autoComplete.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
        return "ParamAssistInfo(boundParams=" + this.getBoundParams() + ", autoComplete=" + this.getAutoComplete() + ")";
    }
}